[package]
name = "gc_example"
version = "0.1.0"
authors = ["Tom Warner <tomwamt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gc = { path = "../gc" }
gc_derive = { path = "../gc_derive" }
